# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96f5ce5ab6101cddd581722c4f90cce8e8bab9225d9e658a72f5eabcdb2b59e44f3329128f2c7a3c2789d492254d2f3a3d398e2621b70cad9475e4493afa1c7f

test:
  secret_key_base: 735f3c5187946bff4bd554c75c79305bda25e8ef500ef309fc74cdce42e1e3d1dc6773622f42a477c948fe08ebac02dc7bbba2fb6e758492cb1a87ed57589189

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
